from __future__ import annotations

import argparse
import json
import os
import re
import socket
import subprocess
import sys
from datetime import datetime
from pathlib import Path


def _default_root() -> Path:
    if getattr(sys, "frozen", False):
        exe_parent = Path(sys.executable).resolve().parent
        if exe_parent.name == "CableTrayAI_Server" and exe_parent.parent.name == "runtime":
            return exe_parent.parent.parent
        return exe_parent
    return Path(__file__).resolve().parents[1]


def _write_start_record(root: Path, host: str, port: int, public_ip: str) -> None:
    docs = root / "docs"
    docs.mkdir(parents=True, exist_ok=True)
    payload = {
        "status": "starting",
        "runner": "portable_exe" if getattr(sys, "frozen", False) else "python",
        "root": str(root),
        "bind": f"{host}:{port}",
        "public_url": f"http://{public_ip}:{port}/",
        "started_at": datetime.now().isoformat(timespec="seconds"),
    }
    (docs / "internal_server_last_start.json").write_text(
        json.dumps(payload, ensure_ascii=False, indent=2),
        encoding="utf-8",
    )


def _local_ipv4_addresses() -> list[str]:
    addresses: set[str] = set()

    def add_address(value: str) -> None:
        for address in re.findall(r"\b(?:\d{1,3}\.){3}\d{1,3}\b", value):
            parts = address.split(".")
            if not all(part.isdigit() and 0 <= int(part) <= 255 for part in parts):
                continue
            if address.startswith(("127.", "169.254.", "255.")) or address.endswith(".255") or address in {"0.0.0.0", "255.255.255.255"}:
                continue
            addresses.add(address)

    try:
        hostname = socket.gethostname()
        for info in socket.getaddrinfo(hostname, None, socket.AF_INET):
            add_address(str(info[4][0]))
    except OSError:
        pass
    try:
        output = subprocess.check_output(["ipconfig"], text=True, encoding="gbk", errors="ignore")
        for line in output.splitlines():
            if "IPv4" not in line and "IP 地址" not in line and "IP Address" not in line:
                continue
            add_address(line)
    except Exception:
        pass
    try:
        output = subprocess.check_output(
            ["netsh", "interface", "ipv4", "show", "addresses"],
            text=True,
            encoding="gbk",
            errors="ignore",
        )
        for line in output.splitlines():
            if "IP Address" not in line and "IP 地址" not in line:
                continue
            add_address(line)
    except Exception:
        pass
    return sorted(addresses)


def _select_public_ip(requested_ip: str) -> str:
    addresses = _local_ipv4_addresses()
    if requested_ip in addresses:
        return requested_ip
    for address in addresses:
        if address.startswith("10."):
            return address
    return addresses[0] if addresses else requested_ip


def _ensure_access_control(root: Path, public_ip: str) -> None:
    config_dir = root / "config"
    config_dir.mkdir(parents=True, exist_ok=True)
    target = config_dir / "access_control.local.json"
    default_allowed = [
        "10.102.15.203",
        "10.102.15.110",
        "10.102.15.102",
        "10.102.15.105",
        "127.0.0.1",
        "::1",
    ]
    data: dict = {}
    if target.exists():
        try:
            data = json.loads(target.read_text(encoding="utf-8-sig"))
        except json.JSONDecodeError:
            data = {}

    allowed = list(data.get("allowed_ips") or [])
    admin = list(data.get("admin_ips") or [])
    for ip in [public_ip, *default_allowed]:
        if ip and ip not in allowed:
            allowed.append(ip)
    for ip in [public_ip, "10.102.15.203", "127.0.0.1", "::1"]:
        if ip and ip not in admin:
            admin.append(ip)

    payload = {
        "enabled": bool(data.get("enabled", True)),
        "server_ip": public_ip,
        "allowed_ips": allowed,
        "admin_ips": admin,
        "trusted_proxy_headers": bool(data.get("trusted_proxy_headers", False)),
        "feedback_store": data.get("feedback_store", "docs/operator_feedback"),
        "manual_entries": data.get("manual_entries", []),
        "notes": [
            "Generated by portable_server.py on startup when local access config is missing or incomplete.",
            "Manual additions from the web UI are preserved by update packages.",
        ],
    }
    target.write_text(json.dumps(payload, ensure_ascii=False, indent=2), encoding="utf-8")


def main() -> int:
    parser = argparse.ArgumentParser(description="CableTrayAI portable web server")
    parser.add_argument("--root", default="", help="CableTrayAI deployment root")
    parser.add_argument("--host", default="0.0.0.0")
    parser.add_argument("--port", type=int, default=8000)
    parser.add_argument("--public-ip", default="10.102.15.203")
    args = parser.parse_args()

    root = Path(args.root).resolve() if args.root else _default_root()
    public_ip = _select_public_ip(args.public_ip)
    os.chdir(root)
    sys.path.insert(0, str(root))

    _ensure_access_control(root, public_ip)
    _write_start_record(root, args.host, args.port, public_ip)

    import uvicorn

    uvicorn.run(
        "apps.api.app.main:app",
        host=args.host,
        port=args.port,
        log_level="info",
        reload=False,
        access_log=False,
        use_colors=False,
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
